// template-react/src/pages/UserManagement/UserManagement.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Space, Modal, Form, Input, Select, message, Popconfirm, Tag } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import {
  listUserUsingGet,
  addUserUsingPost,
  deleteUserUsingDelete,
  updateUserUsingPut,
  getUserByIdUsingGet
} from '@/api/yonghujiekou.ts';

const { Option } = Select;

const UserManagement: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [users, setUsers] = useState<API.UserVO[]>([]);
  const [total, setTotal] = useState(0);
  const [current, setCurrent] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [modalVisible, setModalVisible] = useState(false);
  const [modalTitle, setModalTitle] = useState('添加用户');
  const [form] = Form.useForm();
  const [editingId, setEditingId] = useState<number | null>(null);

  useEffect(() => {
    fetchUsers();
  }, [current, pageSize]);

  const fetchUsers = async () => {
    try {
      setLoading(true);
      const res = await listUserUsingGet({
        current,
        pageSize,
      });

      if (res.data?.data) {
        setUsers(res.data.data.records || []);
        setTotal(res.data.data.total || 0);
      }
    } catch (error) {
      message.error('获取用户列表失败');
    } finally {
      setLoading(false);
    }
  };

  const handleAdd = () => {
    form.resetFields();
    setEditingId(null);
    setModalTitle('添加用户');
    setModalVisible(true);
  };

  const handleEdit = async (id: number) => {
    try {
      setLoading(true);
      const res = await getUserByIdUsingGet({ id });
      if (res.data?.data) {
        form.setFieldsValue({
          userAccount: res.data.data.userAccount,
          userName: res.data.data.userName,
          userRole: res.data.data.userRole,
          userProfile: res.data.data.userProfile,
        });
        setEditingId(id);
        setModalTitle('编辑用户');
        setModalVisible(true);
      }
    } catch (error) {
      message.error('获取用户信息失败');
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id: number) => {
    try {
      setLoading(true);
      await deleteUserUsingDelete({ id });
      message.success('删除用户成功');
      fetchUsers();
    } catch (error) {
      message.error('删除用户失败');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      setLoading(true);

      if (editingId) {
        // 更新用户
        await updateUserUsingPut({
          id: editingId,
          userName: values.userName,
          userProfile: values.userProfile,
        });
        message.success('更新用户成功');
      } else {
        // 添加用户
        await addUserUsingPost({
          userAccount: values.userAccount,
          userPassword: values.userPassword,
          checkPassword: values.checkPassword,
          userName: values.userName,
        });
        message.success('添加用户成功');
      }

      setModalVisible(false);
      fetchUsers();
    } catch (error) {
      message.error('操作失败，请稍后再试');
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    setModalVisible(false);
  };

  const handleTableChange = (pagination: any) => {
    setCurrent(pagination.current);
    setPageSize(pagination.pageSize);
  };

  const columns = [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
    },
    {
      title: '账号',
      dataIndex: 'userAccount',
      key: 'userAccount',
    },
    {
      title: '用户名',
      dataIndex: 'userName',
      key: 'userName',
    },
    {
      title: '角色',
      dataIndex: 'userRole',
      key: 'userRole',
      render: (role: string) => {
        let color = 'blue';
        if (role === 'admin') {
          color = 'red';
        }
        return <Tag color={color}>{role}</Tag>;
      },
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      key: 'createTime',
    },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: API.UserVO) => (
        <Space size="middle">
          <Button
            type="primary"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record.id as number)}
          >
            编辑
          </Button>
          <Popconfirm
            title="确定删除该用户吗？"
            onConfirm={() => handleDelete(record.id as number)}
            okText="确定"
            cancelText="取消"
          >
            <Button type="primary" danger icon={<DeleteOutlined />}>
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <div style={{ marginBottom: 16 }}>
        <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
          添加用户
        </Button>
      </div>

      <Table
        columns={columns}
        dataSource={users}
        rowKey="id"
        loading={loading}
        pagination={{
          current,
          pageSize,
          total,
          showSizeChanger: true,
          showQuickJumper: true,
          showTotal: (total) => `共 ${total} 条`,
        }}
        onChange={handleTableChange}
      />

      <Modal
        title={modalTitle}
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={handleCancel}
        confirmLoading={loading}
      >
        <Form form={form} layout="vertical">
          {!editingId && (
            <Form.Item
              name="userAccount"
              label="账号"
              rules={[
                { required: true, message: '请输入账号' },
                { min: 4, message: '账号长度不能小于4个字符' },
              ]}
            >
              <Input placeholder="请输入账号" />
            </Form.Item>
          )}

          {!editingId && (
            <Form.Item
              name="userPassword"
              label="密码"
              rules={[
                { required: true, message: '请输入密码' },
                { min: 8, message: '密码长度不能小于8个字符' },
              ]}
            >
              <Input.Password placeholder="请输入密码" />
            </Form.Item>
          )}

          {!editingId && (
            <Form.Item
              name="checkPassword"
              label="确认密码"
              dependencies={['userPassword']}
              rules={[
                { required: true, message: '请确认密码' },
                ({ getFieldValue }) => ({
                  validator(_, value) {
                    if (!value || getFieldValue('userPassword') === value) {
                      return Promise.resolve();
                    }
                    return Promise.reject(new Error('两次输入的密码不一致!'));
                  },
                }),
              ]}
            >
              <Input.Password placeholder="请确认密码" />
            </Form.Item>
          )}

          <Form.Item
            name="userName"
            label="用户名"
          >
            <Input placeholder="请输入用户名" />
          </Form.Item>

          {!editingId && (
            <Form.Item
              name="userRole"
              label="角色"
              initialValue="user"
            >
              <Select>
                <Option value="user">普通用户</Option>
                <Option value="admin">管理员</Option>
              </Select>
            </Form.Item>
          )}

          {editingId && (
            <Form.Item
              name="userProfile"
              label="个人简介"
            >
              <Input.TextArea rows={4} placeholder="请输入个人简介" />
            </Form.Item>
          )}
        </Form>
      </Modal>
    </div>
  );
};

export default UserManagement;

// template-vue/src/views/user/UserManagement.vue
<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import type { FormInstance, FormRules } from 'element-plus'
import {addUserUsingPost, deleteUserUsingDelete, listUserUsingGet, updateUserUsingPut} from "@/api/yonghujiekou.ts";

// 表格数据
const tableData = ref([])
const total = ref(0)
const loading = ref(false)

// 查询参数
const queryParams = reactive({
  current: 1,
  pageSize: 10,
  userName: '',
  userAccount: '',
  userRole: ''
})

// 用户表单
const userFormVisible = ref(false)
const userFormTitle = ref('')
const userFormLoading = ref(false)
const userFormRef = ref<FormInstance>()
const userForm = reactive({
  id: undefined,
  userAccount: '',
  userPassword: '',
  checkPassword: '',
  userName: '',
  userRole: 'user',
})

// 表单验证规则
const rules = reactive<FormRules>({
  userAccount: [
    { required: true, message: '请输入账号', trigger: 'blur' },
    { min: 3, max: 20, message: '长度在 3 到 20 个字符', trigger: 'blur' }
  ],
  userPassword: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 6, max: 20, message: '长度在 6 到 20 个字符', trigger: 'blur' }
  ],
  checkPassword: [
    { required: true, message: '请确认密码', trigger: 'blur' },
    { min: 6, max: 20, message: '长度在 6 到 20 个字符', trigger: 'blur' },
    {
      validator: (rule, value, callback) => {
        if (value !== userForm.userPassword) {
          callback(new Error('两次输入密码不一致'))
        } else {
          callback()
        }
      },
      trigger: 'blur'
    }
  ],
  userName: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
    { min: 2, max: 20, message: '长度在 2 到 20 个字符', trigger: 'blur' }
  ],
  userRole: [
    { required: true, message: '请选择用户角色', trigger: 'change' }
  ]
})

// 角色选项
const roleOptions = [
  { value: 'admin', label: '管理员' },
  { value: 'user', label: '普通用户' },
  { value: 'ban', label: '被封禁用户' }
]

// 获取用户列表
const getList = async () => {
  loading.value = true
  try {
    const res = await listUserUsingGet({
      ...queryParams
    })
    if (res.code === 0 && res.data) {
      tableData.value = res.data.records || []
      total.value = res.data.total || 0
    } else {
      ElMessage.error(res.message || '获取用户列表失败')
    }
  } catch (error) {
    console.error('获取用户列表失败', error)
    ElMessage.error('获取用户列表失败')
  } finally {
    loading.value = false
  }
}

// 重置查询参数
const resetQuery = () => {
  Object.assign(queryParams, {
    current: 1,
    pageSize: 10,
    userName: '',
    userAccount: '',
    userRole: ''
  })
  getList()
}

// 处理查询
const handleQuery = () => {
  queryParams.current = 1
  getList()
}

// 处理分页
const handleSizeChange = (pageSize: number) => {
  queryParams.pageSize = pageSize
  getList()
}

const handleCurrentChange = (current: number) => {
  queryParams.current = current
  getList()
}

// 添加用户
const handleAdd = () => {
  userFormTitle.value = '添加用户'
  Object.assign(userForm, {
    id: undefined,
    userAccount: '',
    userPassword: '',
    checkPassword: '',
    userName: '',
    userRole: 'user',
  })
  userFormVisible.value = true
}

// 提交表单
const submitForm = async () => {
  if (!userFormRef.value) return
  
  await userFormRef.value.validate(async (valid) => {
    if (valid) {
      userFormLoading.value = true
      try {
        if (userForm.id) {
          // 更新用户
          const res = await updateUserUsingPut({
            id: userForm.id,
            userAccount: userForm.userAccount,
            userName: userForm.userName,
            userRole: userForm.userRole
          })
          
          if (res.code === 0) {
            ElMessage.success('修改成功')
            userFormVisible.value = false
            getList()
          } else {
            ElMessage.error(res.message || '修改失败')
          }
        } else {
          // 添加用户
          const res = await addUserUsingPost({
            userAccount: userForm.userAccount,
            userPassword: userForm.userPassword,
            checkPassword: userForm.checkPassword,
            userName: userForm.userName
          })
          
          if (res.code === 0) {
            ElMessage.success('添加成功')
            userFormVisible.value = false
            getList()
          } else {
            ElMessage.error(res.message || '添加失败')
          }
        }
      } catch (error) {
        console.error('操作失败', error)
        ElMessage.error('操作失败')
      } finally {
        userFormLoading.value = false
      }
    }
  })
}

// 编辑用户
const handleEdit = (row: any) => {
  userFormTitle.value = '编辑用户'
  Object.assign(userForm, {
    id: row.id,
    userAccount: row.userAccount,
    userPassword: '',
    checkPassword: '',
    userName: row.userName,
    userRole: row.userRole
  })
  userFormVisible.value = true
}

// 删除用户
const handleDelete = (id: number) => {
  ElMessageBox.confirm('确认删除该用户?', '警告', {
    confirmButtonText: '确认',
    cancelButtonText: '取消',
    type: 'warning'
  }).then(async () => {
    try {
      const res = await deleteUserUsingDelete({
        id
      })
      
      if (res.code === 0) {
        ElMessage.success('删除成功')
        getList()
      } else {
        ElMessage.error(res.message || '删除失败')
      }
    } catch (error) {
      console.error('删除失败', error)
      ElMessage.error('删除失败')
    }
  }).catch(() => {})
}

onMounted(() => {
  getList()
})
</script>

<template>
  <div class="page-container">
    <!-- 搜索区域 -->
    <el-card>
      <el-form :model="queryParams" ref="queryForm" :inline="true">
        <el-form-item label="用户名" prop="userName">
          <el-input
            v-model="queryParams.userName"
            placeholder="请输入用户名"
            clearable
            @keyup.enter="handleQuery"
          />
        </el-form-item>
        <el-form-item label="账号" prop="userAccount">
          <el-input
            v-model="queryParams.userAccount"
            placeholder="请输入账号"
            clearable
            @keyup.enter="handleQuery"
          />
        </el-form-item>
        <el-form-item label="角色" prop="userRole">
          <el-select v-model="queryParams.userRole" placeholder="请选择角色" clearable>
            <el-option
              v-for="item in roleOptions"
              :key="item.value"
              :label="item.label"
              :value="item.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleQuery">查询</el-button>
          <el-button @click="resetQuery">重置</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <!-- 表格区域 -->
    <el-card style="margin-top: 20px">
      <div class="table-operations">
        <el-button type="primary" @click="handleAdd">添加用户</el-button>
      </div>
      
      <el-table
        v-loading="loading"
        :data="tableData"
        border
        style="width: 100%"
      >
        <el-table-column prop="id" label="ID" width="80" />
        <el-table-column prop="userAccount" label="账号" width="120" />
        <el-table-column prop="userName" label="用户名" width="120" />
        <el-table-column prop="userRole" label="角色" width="120">
          <template #default="{ row }">
            <el-tag
              :type="row.userRole === 'admin' ? 'danger' : row.userRole === 'user' ? 'primary' : 'info'"
            >
              {{ row.userRole === 'admin' ? '管理员' : row.userRole === 'user' ? '普通用户' : '被封禁' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="createTime" label="创建时间" width="180" />
        <el-table-column prop="updateTime" label="更新时间" width="180" />
        <el-table-column label="操作" fixed="right" width="150">
          <template #default="{ row }">
            <el-button
              size="small"
              type="primary"
              text
              @click="handleEdit(row)"
            >
              编辑
            </el-button>
            <el-button
              size="small"
              type="danger"
              text
              @click="handleDelete(row.id)"
            >
              删除
            </el-button>
          </template>
        </el-table-column>
      </el-table>
      
      <!-- 分页 -->
      <div class="pagination">
        <el-pagination
          v-model:current-page="queryParams.current"
          v-model:page-size="queryParams.pageSize"
          :page-sizes="[10, 20, 50, 100]"
          layout="total, sizes, prev, pager, next, jumper"
          :total="total"
          @size-change="handleSizeChange"
          @current-change="handleCurrentChange"
        />
      </div>
    </el-card>
    
    <!-- 用户表单 -->
    <el-dialog
      v-model="userFormVisible"
      :title="userFormTitle"
      width="500px"
      append-to-body
    >
      <el-form
        ref="userFormRef"
        :model="userForm"
        :rules="rules"
        label-width="100px"
      >
        <el-form-item label="账号" prop="userAccount">
          <el-input v-model="userForm.userAccount" placeholder="请输入账号" />
        </el-form-item>
        <el-form-item label="密码" prop="userPassword" v-if="!userForm.id">
          <el-input
            v-model="userForm.userPassword"
            type="password"
            placeholder="请输入密码"
            show-password
          />
        </el-form-item>
        <el-form-item label="确认密码" prop="checkPassword" v-if="!userForm.id">
          <el-input
            v-model="userForm.checkPassword"
            type="password"
            placeholder="请确认密码"
            show-password
          />
        </el-form-item>
        <el-form-item label="用户名" prop="userName">
          <el-input v-model="userForm.userName" placeholder="请输入用户名" />
        </el-form-item>
        <el-form-item label="角色" prop="userRole">
          <el-select v-model="userForm.userRole" placeholder="请选择角色">
            <el-option
              v-for="item in roleOptions"
              :key="item.value"
              :label="item.label"
              :value="item.value"
            />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button @click="userFormVisible = false">取消</el-button>
          <el-button type="primary" @click="submitForm" :loading="userFormLoading">
            确认
          </el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.page-container {
  padding: 20px;
}
</style>
